baseURL: "https://runbooks.thaum.xyz"
languageCode: "en-us"
title: "Ankhmorpork runbooks"

theme: book

params:
  BookRepo: "https://github.com/thaum-xyz/runbooks"
  BookEditPath: "edit/main"
  BookSearch: true
  BookSection: "runbooks"
  #BookMenuBundle: "/menu"

